# Project: CAUTRUC_BAI5
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = CAUTRUC_BAI5.o
LINKOBJ  = CAUTRUC_BAI5.o
LIBS     = -L"D:/IT/Code/App_C++/MinGW64/lib" -L"D:/IT/Code/App_C++/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/IT/Code/App_C++/MinGW64/include" -I"D:/IT/Code/App_C++/MinGW64/x86_64-w64-mingw32/include" -I"D:/IT/Code/App_C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/IT/Code/App_C++/MinGW64/include" -I"D:/IT/Code/App_C++/MinGW64/x86_64-w64-mingw32/include" -I"D:/IT/Code/App_C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/IT/Code/App_C++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = CAUTRUC_BAI5.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

CAUTRUC_BAI5.o: CAUTRUC_BAI5.cpp
	$(CPP) -c CAUTRUC_BAI5.cpp -o CAUTRUC_BAI5.o $(CXXFLAGS)
